version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}